#!/bin/bash
# Health check fix script - generated by iteration 1
# Run this to complete the fix

set -e
cd /workspace

# Step 1: Install dev dependencies
echo "Installing dev dependencies..."
uv pip install -e ".[dev]"

# Step 2: Verify installation
echo "Verifying packages..."
uv pip list | grep -E "(amplifier|copilot)"

# Step 3: Run type check
echo "Running pyright..."
uv run pyright amplifier_module_provider_github_copilot/ 2>&1 | tail -30

# Step 4: Run tests
echo "Running tests..."
uv run pytest tests/ -v 2>&1 | tail -50

# Step 5: Commit if successful
echo "Committing changes..."
git add SCRATCH.md STATE.yaml
git commit -m "docs: document health check root cause (iteration 1)

Root cause identified: environment configuration issues, not code bugs.
- Pyright errors (85): amplifier-core not installed in .venv
- Test failures (11): pytest using system Python, not venv

Added blocker to STATE.yaml with fix instructions:
  uv pip install -e \".[dev]\"

Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>"

echo "Done! Health check fix complete."
